### PR TITLE
Create Nikhil

### PR DESCRIPTION
**Pull request by nvinai**
pls add me :P

### CODE REVIEW

**Review by nvinai — COMMENTED** [review]
should i create a .md file?

**Comment by nchlswhttkr** [comment]
Hey @nvinai,

Yep, you should create a `.md` file, make sure you [follow the template](https://nchlswhttkr.github.io/hacktoberfest-2019/contribute/#3-create-your-participant-page) so that your name will show up!

**Comment by nvinai** [comment]
Thank you Nicholas!

**Review by nchlswhttkr — APPROVED** [review]
LGTM :shipit:

Awesome work Nikhil, you fixed the file 👍

**Pull request merged**
